In [5]:
import pandas as pd
#input csv file
df = pd.read_csv("c:\\Users\\ankit\\Downloads\\Titanic Dataset.csv")
print("our DataFrame....",df)

our DataFrame....      PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0
2                       Myles, Mr. Thomas Francis    male  62.0      0      0
3                                Wirz, Mr. Albert    male  27.0      0      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1
..                                            ...     ...   ...    ...    ...
413                            Spector, Mr. Woolf    male   NaN      0      0
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0
416                           Ware, Mr. Frederick    male   NaN      0      0
417                      Peter, Master. Michael J    male   NaN      1      1

                 Ticket      Fare Cabin Embarked
0                330911    7.8292   NaN        Q
1                363272    7.0000   NaN        S
2                240276    9.6875   NaN        Q
3                315154    8.6625   NaN        S
4               3101298   12.2875   NaN        S
..                  ...       ...   ...      ...
413           A.5. 3236    8.0500   NaN        S
414            PC 17758  108.9000  C105        C
415  SOTON/O.Q. 3101262    7.2500   NaN        S
416              359309    8.0500   NaN        S
417                2668   22.3583   NaN        C

[418 rows x 12 columns]

In [8]:
df.sample(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
124,1016,0,3,"Kennedy, Mr. John",male,NaN,0,0,368783,7.75,NaN,Q
260,1152,0,3,"de Messemaeker, Mr. Guillaume Joseph",male,36.5,1,0,345572,17.40,NaN,S
203,1095,1,2,"Quick, Miss. Winifred Vera",female,8.0,1,1,26360,26.00,NaN,S

In [9]:
selected_passengers = df[(df['Fare']>100)&(df['Age']<30)]
names=selected_passengers['Name']
names

53                            Fortune, Miss. Ethel Flora
64                           Ryerson, Master. John Borie
156                                    Bird, Miss. Ellen
184    Douglas, Mrs. Frederick Charles (Mary Helene B...
196                      Spedden, Master. Robert Douglas
252                             Clark, Mr. Walter Miller
272        Clark, Mrs. Walter Miller (Virginia McDowell)
Name: Name, dtype: str

In [11]:
sltd_pass=df.sort_values(by='Age',ascending=False).head(5)
sltd_pass[['Name','Age','Survived']]

                                                  Name   Age  Survived
96   Cavendish, Mrs. Tyrell William (Julia Florence...  76.0         1
81                                  Straus, Mr. Isidor  67.0         0
236                           Warren, Mr. Frank Manley  64.0         0
179  Compton, Mrs. Alexander Taylor (Mary Eliza Ing...  64.0         1
305  Crosby, Mrs. Edward Gifford (Catherine Elizabe...  64.0         1

In [12]:
n = df['Cabin'].isna().sum()
print(n)

327

In [13]:
df.sample(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
131,1023,0,1,"Gracie, Col. Archibald IV",male,53.0,0,0,113780,28.500,C51,C
55,947,0,3,"Rice, Master. Albert",male,10.0,4,1,382652,29.125,NaN,Q
325,1217,0,3,"Assam, Mr. Ali",male,23.0,0,0,SOTON/O.Q. 3101309,7.050,NaN,S

In [14]:
df['Title'] = df['Name'].str.split(',').str.get(1).str.strip().str.split().str.get(0)
df['Title'].unique()[:5]

array(['Mr.', 'Mrs.', 'Miss.', 'Master.', 'Ms.'], dtype=object)

In [15]:
df['Age'].fillna(df['Age'].mean(),inplace=True)
df['Age'].isna().sum()

C:\Users\ankit\AppData\Local\Temp\ipykernel_11084\2663981579.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Age'].fillna(df['Age'].mean(),inplace=True)

np.int64(86)

In [16]:
df['Fare'].sort_values(ascending=False).head(10)

343    512.3292
69     263.0000
53     263.0000
59     262.3750
64     262.3750
375    262.3750
142    262.3750
24     262.3750
184    247.5208
202    227.5250
Name: Fare, dtype: float64

In [17]:
ndf = df[df['Survived']==0]
ndf.loc[ndf['Age'].idxmin(),'Name']

'Danbom, Master. Gilbert Sigvard Emanuel'

In [18]:
df[df['Name'].str.get(0) == 'A'].head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title
8,900,1,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C,Mrs.
17,909,0,3,"Assaf, Mr. Gerios",male,21.0,0,0,2692,7.2250,NaN,C,Mr.
19,911,1,3,"Assaf Khalil, Mrs. Mariana (Miriam"")""",female,45.0,0,0,2696,7.2250,NaN,C,Mrs.
57,949,0,3,"Abelseth, Mr. Olaus Jorgensen",male,25.0,0,0,348122,7.6500,F G63,S,Mr.
78,970,0,2,"Aldworth, Mr. Charles Augustus",male,30.0,0,0,248744,13.0000,NaN,S,Mr.

In [19]:
df['FamilySize'] = df['SibSp'] + df['Parch']
df[(df['FamilySize']>3)].head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title,FamilySize
24,916,1,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C,Mrs.,4
53,945,1,1,"Fortune, Miss. Ethel Flora",female,28.0,3,2,19950,263.0000,C23 C25 C27,S,Miss.,5
55,947,0,3,"Rice, Master. Albert",male,10.0,4,1,382652,29.1250,NaN,Q,Master.,5
64,956,0,1,"Ryerson, Master. John Borie",male,13.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,Master.,4
69,961,1,1,"Fortune, Mrs. Mark (Mary McDougald)",female,60.0,1,4,19950,263.0000,C23 C25 C27,S,Mrs.,5
132,1024,1,3,"Lefebre, Mrs. Frank (Frances)",female,NaN,0,4,4133,25.4667,NaN,S,Mrs.,4
139,1031,0,3,"Goodwin, Mr. Charles Frederick",male,40.0,1,6,CA 2144,46.9000,NaN,S,Mr.,7
140,1032,1,3,"Goodwin, Miss. Jessie Allis",female,10.0,5,2,CA 2144,46.9000,NaN,S,Miss.,7
142,1034,0,1,"Ryerson, Mr. Arthur Larned",male,61.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C,Mr.,4
154,1046,0,3,"Asplund, Master. Filip Oscar",male,13.0,4,2,347077,31.3875,NaN,S,Master.,6

In [20]:
df['FarePerPerson']=(df['Fare'])/(df['FamilySize']+1)
df[df['FarePerPerson'] ==  df['FarePerPerson'].max()][['Name','FarePerPerson']]

                            Name  FarePerPerson
59   Chaudanson, Miss. Victorine        262.375
375     Bowen, Miss. Grace Scott        262.375